version: '3.9'

services:
  webserver:
    container_name: Laravel-webServer
    build:
      context: .
      dockerfile: ./php/Dockerfile
    volumes:
      - ./laravel-app:/var/www/html
    ports:
      - 80:80
    networks:
      - my_network
    depends_on:
      - mysql

  mysql:
    container_name: mysql-db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example_password
      MYSQL_DATABASE: laravel
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./create_table.sql:/docker-entrypoint-initdb.d/create_table.sql
    networks:
      - my_network

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: example_password
    networks:
      - my_network

networks:
  my_network:
